---
# Site configuration
domain_name: "paxa.dev"
domain_subdomains:
  - "www"
  - "pages"

# SSL Certificate configuration
ssl_certificate_email: "sistematico@gmail.com"
ssl_certificate_staging: false
ssl_certificate_force_renewal: false
certbot_auto_renew: true

# Application configuration
app_port: 3033
github_pages_host: "sistematico.github.io"
github_pages_path: "/startpages"

# Nginx SSL settings
nginx_ssl_protocols: "TLSv1.2 TLSv1.3"
nginx_ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384"
nginx_ssl_prefer_server_ciphers: "off"

# Systemd service configuration
service_name: "{{ domain_name }}"
service_description: "{{ domain_name | title }} Next.js Application"
service_user: "nginx"
service_group: "nginx"
service_environment: "NODE_ENV=production"
service_working_directory: "/var/www/{{ domain_name }}"
service_exec_start: "/home/{{ service_user }}/.bun/bin/bun run start"
service_restart: "always"
service_restart_sec: "10s"

# Service management
service_enabled: true
service_initial_state: "started"
service_auto_restart: true

# Sudoers configuration
service_sudoers_name: "{{ domain_name | replace('.', '_') }}"

# Resource limits
service_limit_nofile: "65535"
service_limit_nproc: "2048"

# Security settings
service_security_no_new_privileges: true
service_security_private_tmp: true
service_security_protect_system: "full"

# Optional memory limits (uncomment to enable)
# service_memory_accounting: true
# service_memory_high: "800M"
# service_memory_max: "900M"

# Optional startup limits (uncomment to enable)
# service_start_limit_interval_sec: "60"
# service_start_limit_burst: "3"